version: 2

sources:
  - name: ecommerce_data_modelling # Source system name
    database: ECOMMERCE_DWH # Optional: database where source is stored
    schema: ECOMMERCE_STAGING # Schema containing the source tables
    tables:
      - name: ADDRESSES # Table name as it exists in the database
      - name: CATEGORIES
      - name: CUSTOMERS
      - name: ORDERS
      - name: ORDER_ITEMS
      - name: PAYMENTS
      - name: PRODUCTS
